services:
  mail_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail_server_vlan30
    ports:
      - "25:25"
    volumes:
      - ./db:/app/db
    user: "1000:1000"
    restart: always

networks:
  default:
    driver: bridge
